trigger:
  branches:
    include:
    - master
  paths:
    include:
    - .cicd
    - cli

pr: none

resources:
  repositories:
  - repository: platform-ops
    type: github
    name: qbituniverse/platform-ops
    endpoint: qbituniverse

stages:
- stage: DockerBuild
  displayName: 'Build qbitcli'
  pool:
    name: self-hosted-ado-agents
    demands:
    - agent.name -equals ado-agent-arm64
  variables:
    imageDockerfile: .cicd/docker/Dockerfile-qbitcli
    imageRepository: qbituniverse/qbitcli
    imageTag: latest
    imageArchitecture: linux/amd64,linux/arm64
  jobs:
  - job: DockerBuild
    displayName: 'Build qbitcli'
    timeoutInMinutes: 0
    steps:
    - template: azure-devops/builds/dockerhub-login.yaml@platform-ops

    - template: azure-devops/builds/create-buildx.yaml@platform-ops
      parameters:
        buildNumber: $(Build.BuildId)

    - template: azure-devops/builds/build-push-docker-image-multi-arch.yaml@platform-ops
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageRepository: $(imageRepository)
        imageTag: $(imageTag)
        imageArchitecture: $(imageArchitecture)

    - template: azure-devops/builds/delete-buildx.yaml@platform-ops
      parameters:
        buildNumber: $(Build.BuildId)